apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
  namespace: demo
spec:
  scaleTargetRef:
    name: queue-worker

  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 30

  triggers:
  - type: redis
    metadata:
      address: redis.demo.svc.cluster.local:6379
      listName: orders
      listLength: "5"
